name: ${project.name}
main: ${project.groupId}.${project.artifactId}
author: shinji257
website: http://dev.bukkit.org/server-mods/aop/
version: ${project.version} (${timestamp})

commands:
    opme:
        description: Allows players to give OP status to themself.
        usage: /<command>
    deopme:
        description: Allows players to remove OP status from themself.
        usage: /<command>
    aop:
        description: Plugin management
        usage: /<command>

permissions:
    aop.use:
        description: Gives access to use /opme
        default: op
    aop.notify:
        description: Gives ability to recieve notification when a monitored command is used
        default: op
    aop.reload:
        description: Allows reloading the plugin configuration
        default: op
    aop.bypass.opdrop:
        description: Bypass the automatic op drop on quit (when enabled)
        default: false        
    aop.bypass.intercept:
        description: Bypass the intercept check for op/deop (when enabled)
        default: false
