name: aOP
main: org.shinji257.aop.aOP
author: shinji257
website: http://dev.bukkit.org/server-mods/aop/
version: 2.3
softdepend: [Vault]

commands:
    opme:
        description: Allows players to give OP status to themself.
        usage: /<command> - enable OP status on yourself.
    deopme:
        description: Allows players to remove OP status from themself.
        usage: /<command> - disable OP status on yourself.
    aop:
        description: Plugin management
        usage: /<command> - Plugin management

permissions:
    aop.use:
        description: Gives access to use /opme
        default: op
    aop.notify:
        description: Gives ability to recieve notification when a monitored command is used
        default: op
    aop.reload:
        description: Allows reloading the plugin configuration
        default: op
    aop.bypass.opdrop:
        description: Bypass the automatic op drop on quit
        default: false
